### ISSUE TITLE
Are you looking for a maintainer?

### ISSUE THREAD

**Issue by devth** [bmabey/clj-campfire#4]

**Comment by bmabey** [comment]
Hi @devth, for some reason I haven't been getting notifications for this project.  It may be related to the fact that I no longer work at LeadTune and the emails were setup to go to the devs email account.

Anyways, I could review and merge in the pending PRs but if you are anxious to take the project to the next level and maintain it that would be cool by me too.  Thoughts?

**Comment by bmabey** [comment]
I've merged in the commits and [released](https://clojars.org/clj-campfire) `v2.1.0`.  Still interested in taking over?

**Comment by devth** [comment]
I'm willing to do it if you don't want to or are too busy, but I have no plans to make any big changes. Just getting a few PR's accepted here and there would be great. Thanks.
